---
# tasks file for docker
 - name: create image docker 
   docker_image:
    name: MyApp
    build:
    path: /var/lib/jenkins/workspace/MyApp
    pull: no
    source: build 
    state: present
    force_source: true
 - name: run container docker
   docker_container:
    name: myapp_container
    image: MyApp
    state: started
    recreate: true
    ports:
     - "4200:80"
